- hosts: all
  remote_user: deep
  become: yes
  become_method: sudo
  tasks:
  - name: upgrade all packages
    dnf:
      name: "*"
      state: latest  
  - name: Autoremove unneeded packages installed as dependencies
    dnf:
      autoremove: yes
